apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: kakfa
      image: lensesio/fast-data-dev:latest
      imagePullPolicy: Always
      env:
      - name: ADV_HOST
        value: "192.168.1.164"
      - name: BROKER_PORT
        value: "30092"
      - name: ZK_PORT
        value: "30181"
      - name: REGISTRY_PORT
        value: "30081"
      - name: REST_PORT
        value: "30082"            
      - name: CONNECT_PORT
        value: "30083"   
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: web
      port: 3030
      targetPort: 3030
      nodePort: 30030
    - name: zk
      port: 2181
      targetPort: 30181
      nodePort: 30181
    - name: schema
      port: 8081
      targetPort: 30081
      nodePort: 30081
    - name: rest
      port: 8082
      targetPort: 30082
      nodePort: 30082
    - name: connect
      port: 8083
      targetPort: 30083
      nodePort: 30083
    - name: jmx1
      port: 9581
      targetPort: 9581
      nodePort: 30581
    - name: jmx2
      port: 9582
      targetPort: 9582
      nodePort: 30582
    - name: jmx3
      port: 9583
      targetPort: 9583
      nodePort: 30583
    - name: jmx4
      port: 9584
      targetPort: 9584
      nodePort: 30584
    - name: jmx5
      port: 9585
      targetPort: 9585
      nodePort: 30585
    - name: broker
      port: 9092
      targetPort: 30092
      nodePort: 30092
